package br.com.fiap.SkillBridge.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * ============================================================
 *  ENTIDADE: Vaga
 * ============================================================
 * Representa uma oportunidade de trabalho dentro da plataforma
 * SkillBridge, sendo utilizada:
 *
 * - Pela camada de persistência (Spring Data JPA) para mapear
 *   a tabela TB_VAGA no banco de dados.
 * - Pela camada de serviço e controllers para exibir e filtrar
 *   vagas para os candidatos.
 *
 * ------------------------------------------------------------
 *  MAPEAMENTO DA TABELA NO BANCO (Flyway / DDL)
 * ------------------------------------------------------------
 *  CREATE TABLE TB_VAGA
 *  (
 *      ID             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 *      NM_TITULO      VARCHAR(120),
 *      DS_REQUISITOS  VARCHAR(300),
 *      NM_EMPRESA     VARCHAR(100),
 *      DS_LOCAL       VARCHAR(200),
 *      CONSTRAINT pk_vaga PRIMARY KEY (ID)
 *  );
 *
 * ------------------------------------------------------------
 *  REGRAS GERAIS DE MODELAGEM
 * ------------------------------------------------------------
 * - Bean Validation:
 *   Os campos anotados com @NotBlank e @Size são validados
 *   automaticamente pelo Spring ao receber um VagaRequest.
 *
 * - Mensagens de erro:
 *   As mensagens usam chaves i18n (ex.: {vaga.titulo.not-blank})
 *   definidas em messages.properties para permitir tradução.
 *
 * - Alinhamento com DTOs:
 *   Os tamanhos de @Size(max = ...) acompanham os limites de
 *   coluna definidos na DDL e no VagaRequest (DTO de entrada).
 *
 * - Convenção de nomes:
 *   Os nomes das colunas seguem o padrão:
 *     ID_*        → chave primária / identificador
 *     NM_*        → campos de “nome” / texto curto
 *     DS_*        → campos de “descrição” / texto descritivo
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "TB_VAGA")
public class Vaga {

    // =========================================================
    //  CAMPO: ID
    // =========================================================
    /**
     * Identificador único da vaga.
     *
     * Características:
     * - Mapeado para a coluna ID (BIGINT) em TB_VAGA.
     * - Gerado automaticamente pelo banco (IDENTITY).
     * - Usado como chave primária nas operações de CRUD.
     *
     * Observação:
     * - Não deve ser preenchido manualmente na criação da vaga.
     *   O valor é atribuído pelo banco ao salvar a entidade.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID") // BIGINT GENERATED BY DEFAULT AS IDENTITY
    private Long id;

    // =========================================================
    //  CAMPO: titulo
    // =========================================================
    /**
     * Título “comercial” da vaga.
     *
     * Exemplos:
     * - "Desenvolvedor Java Pleno"
     * - "Analista de Dados Jr."
     * - "Frontend React Developer"
     *
     * Regras de validação:
     * - Não pode ser vazio (NotBlank).
     * - Limite máximo de 120 caracteres (Size).
     *
     * Mapeamento:
     * - Coluna: NM_TITULO
     * - Tipo: VARCHAR(120)
     *
     * Uso na aplicação:
     * - Exibido nos cards/listas de vagas.
     * - Utilizado em buscas e filtros de texto livres.
     */
    @NotBlank(message = "{vaga.titulo.not-blank}")
    @Size(max = 120, message = "{vaga.titulo.size}") // VARCHAR(120)
    @Column(name = "NM_TITULO", length = 120)
    private String titulo;

    // =========================================================
    //  CAMPO: requisitos
    // =========================================================
    /**
     * Resumo dos principais requisitos da vaga.
     *
     * Exemplos:
     * - "Java 11+, Spring Boot, REST, SQL"
     * - "React, TypeScript, testes automatizados"
     * - "SQL, Python, ETL básicos, Power BI"
     *
     * Regras de validação:
     * - Não pode ser vazio (NotBlank).
     * - Limite máximo de 300 caracteres (Size).
     *
     * Mapeamento:
     * - Coluna: DS_REQUISITOS
     * - Tipo: VARCHAR(300)
     *
     * Uso na aplicação:
     * - Exibido no detalhe da vaga e em telas de listagem.
     * - Ajuda o candidato a identificar rapidamente se tem o perfil.
     */
    @NotBlank(message = "{vaga.requisitos.not-blank}")
    @Size(max = 300, message = "{vaga.requisitos.size}") // VARCHAR(300)
    @Column(name = "DS_REQUISITOS", length = 300)
    private String requisitos;

    // =========================================================
    //  CAMPO: empresa
    // =========================================================
    /**
     * Nome da empresa responsável pela vaga.
     *
     * Exemplos:
     * - "Tech Solutions"
     * - "UI Labs"
     * - "DataCorp"
     *
     * Regras de validação:
     * - Não pode ser vazio (NotBlank).
     * - Limite máximo de 100 caracteres (Size).
     *
     * Mapeamento:
     * - Coluna: NM_EMPRESA
     * - Tipo: VARCHAR(100)
     *
     * Uso na aplicação:
     * - Exibição direta para o candidato.
     * - Pode ser usado em filtros por empresa.
     */
    @NotBlank(message = "{vaga.empresa.not-blank}")
    @Size(max = 100, message = "{vaga.empresa.size}") // VARCHAR(100)
    @Column(name = "NM_EMPRESA", length = 100)
    private String empresa;

    // =========================================================
    //  CAMPO: local
    // =========================================================
    /**
     * Localização ou regime de trabalho da vaga.
     *
     * Exemplos:
     * - "São Paulo, SP - Híbrido"
     * - "Remoto"
     * - "Campinas, SP - Presencial"
     *
     * Regras de validação:
     * - Não pode ser vazio (NotBlank).
     * - Limite máximo de 200 caracteres (Size).
     *
     * Mapeamento:
     * - Coluna: DS_LOCAL
     * - Tipo: VARCHAR(200)
     *
     * Uso na aplicação:
     * - Exibido tanto na listagem quanto no detalhe da vaga.
     * - Pode ser usado em filtros por cidade/região/regime.
     */
    @NotBlank(message = "{vaga.local.not-blank}")
    @Size(max = 200, message = "{vaga.local.size}") // VARCHAR(200)
    @Column(name = "DS_LOCAL", length = 200)
    private String local;
}
