CREATE TABLE vaga
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo     VARCHAR(120),
    requisitos VARCHAR(300),
    empresa    VARCHAR(100),
    local      VARCHAR(200),
    CONSTRAINT pk_vaga PRIMARY KEY (id)
);
