CREATE TABLE TB_VAGA
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- identificador único da vaga
    NM_TITULO      VARCHAR(120),                                     -- nome/título da vaga (ex.: Dev .NET Júnior)
    DS_REQUISITOS  VARCHAR(300),                                     -- descrição dos requisitos desejados para a vaga
    NM_EMPRESA     VARCHAR(100),                                     -- nome da empresa contratante
    DS_LOCAL       VARCHAR(200),                                     -- descrição do local da vaga (cidade, bairro, remoto, etc.)
    CONSTRAINT pk_vaga PRIMARY KEY (ID)                              -- chave primária da tabela
);
