CREATE TABLE candidatura
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vaga_id          BIGINT NOT NULL,
    nome             VARCHAR(150) NOT NULL,
    email            VARCHAR(200),
    telefone         VARCHAR(50),
    curriculo        TEXT,
    status           VARCHAR(50) DEFAULT 'PENDENTE',
    data_aplicacao   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_candidatura PRIMARY KEY (id),
    CONSTRAINT fk_candidatura_vaga FOREIGN KEY (vaga_id) REFERENCES vaga (id) ON DELETE CASCADE
);

CREATE INDEX idx_candidatura_vaga_id ON candidatura (vaga_id);